POST http://localhost:4000/wilders
Content-Type: application/json

{
  "firstName": "Fafafa",
  "lastName": "Lalala",
  "isTrainer": false,
  "schoolName": "Paris",
  "skillsName": ["CSS", "PHP", "JavaScript"]

}